stages:
  - test
  - build

image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

test-job:
  stage: test
  script:
    - echo "---> Building test image and running tests"
    - docker-compose --project-name=$CI_BUILD_ID build tests-pipeline
    - docker-compose --project-name=$CI_BUILD_ID run --rm tests-pipeline
  after_script:
    - docker-compose --project-name=$CI_BUILD_ID down -v --rmi local

build-job:
  stage: build
  only:
    - tags
  script:
    - echo "---> Build latest image"
    - docker build --pull -t pan-toksyczny:latest .
    - docker push pan-toksyczny:latest
