stages:
  - test
  - build
  - deploy

image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip ansible
  - pip install docker-compose
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

test-job:
  stage: test
  script:
    - echo "---> Building test image and running tests"
    - docker-compose --project-name=$CI_BUILD_ID build tests-pipeline
    - docker-compose --project-name=$CI_BUILD_ID run --rm tests-pipeline
  after_script:
    - docker-compose --project-name=$CI_BUILD_ID down -v --rmi local

build-job:
  stage: build
  only:
    - tags
    - web
  script:
    - echo "---> Build latest image"
    - docker build -t registry.gitlab.com/mateusz.probachta/pan-toksyczny:latest .
    - docker push registry.gitlab.com/mateusz.probachta/pan-toksyczny:latest

deploy-job:
  stage: deploy
  only:
    - tags
    - web
  script:
    - echo "---> deploy on ${DEPLOY_HOST}"
    - ping -w 5 ${DEPLOY_HOST}
    - ansible-playbook --inventory=${DEPLOY_HOST}, deploy/deploy.yml
