version: "3"

services:
  repl:
    image: clojure:lein
    volumes:
      - ./:$PWD
    working_dir: $PWD
    environment:
      - AQICN_TOKEN=$AQICN_TOKEN
      - PAGE_ACCESS_TOKEN=$PAGE_ACCESS_TOKEN
    ports:
      - "3000:3000"
      - "7000:7000"
    command: lein repl :headless :host 0.0.0.0 :port 7000

  tests:
    image: clojure:lein
    volumes:
      - ./:$PWD
    working_dir: $PWD
    environment:
      - AQICN_TOKEN=$AQICN_TOKEN
      - PAGE_ACCESS_TOKEN=$PAGE_ACCESS_TOKEN
    tty: true
    command: lein test-refresh

  app:
    build: .

  tests-pipeline:
    build:
      context: .
      dockerfile: ./Dockerfile.tests
