version: "3.7"

x-base: &base
  image: registry.gitlab.com/mateusz.probachta/pan-toksyczny:latest
  volumes:
    - ./db:/db
    - ./log:/log
  environment:
    - AQICN_TOKEN=$AQICN_TOKEN
    - PAGE_ACCESS_TOKEN=$PAGE_ACCESS_TOKEN


services:
  app:
    << : *base
    restart: always
    ports:
      - "3000:3000"

  migrate:
    << : *base
    command: java -jar /pan-toksyczny.jar migrate
