version: "3"

services:
  app:
    image: registry.gitlab.com/mateusz.probachta/pan-toksyczny:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./db:/db
      - ./log:/log
      - ./hornetq-data:/hornetq-data
    environment:
      - AQICN_TOKEN=$AQICN_TOKEN
      - PAGE_ACCESS_TOKEN=$PAGE_ACCESS_TOKEN
